Repository FACN8/Donator, pull requests merged in 2020-03, with the labels that each got.

#25 Adds Navigation Circle and donation page
  package-lock.json
  package.json
  src/App.jsx
  src/assets/donationBoxes.jpg
  src/assets/landingPage.jpg
  src/components/DefaultHeader/index.jsx
  src/components/DeliveryTime/index.jsx
  src/components/Dialog/index.jsx
  src/components/DonationDropDown/index.jsx
  src/components/DonationOther/index.jsx
  src/components/Hamburger/index.jsx
  src/components/Hamburger/style.css
  src/components/HomeHeader/index.jsx
  src/components/HomeHeader/style.css
  src/components/NavCircle/index.jsx
  src/components/NavCircle/style.css
  src/components/OrgCard/index.jsx
  src/screens/DonationPage/index.jsx
  src/screens/LandingPage/index.jsx
  src/screens/OrgInfo/index.jsx
Labels: merge-conflicts

#27 General fixes
  package-lock.json
  package.json
  src/App.jsx
  src/components/Chart/index.jsx
  src/components/Chart/style.css
  src/components/Dialog/index.jsx
  src/components/DonationsCards/index.jsx
  src/components/DonationsCards/style.css
  src/components/FilterStats/index.jsx
  src/components/Footer/index.jsx
  src/components/HomeHeader/style.css
  src/components/NavCircle/index.jsx
  src/components/OrgCard/index.jsx
  src/components/SignUpInputs/index.jsx
  src/components/UserDetail/index.jsx
  src/components/UserDetail/style.css
  src/components/UserStats/index.jsx
  src/components/UserStats/style.css
  src/index.jsx
  src/screens/DonationPage/index.jsx
  src/screens/LandingPage/index.jsx
  src/screens/LandingPage/style.css
  src/screens/OrgInfo/index.jsx
  src/screens/OrgInfo/style.css
  src/screens/Profile/index.jsx
  src/screens/Profile/style.css
  src/screens/SignUp/index.jsx
  src/screens/SignUp/style.css
Labels: general fixes, in-progress

#29 working on the landing page
  src/components/OrgBubble/style.css
  src/components/Video/index.jsx
  src/components/Video/style.css
  src/screens/LandingPage/index.jsx
  src/screens/LandingPage/style.css
Labels: Mobile-First

#41 connects to the server to get data
  src/components/Dashboard/index.jsx
  src/components/Dialog/index.jsx
  src/components/LoginInput/index.jsx
  src/components/Message/index.jsx
  src/components/OrgBubble/index.jsx
  src/components/OrgCard/index.jsx
  src/components/OrgStatistic/index.jsx
  src/components/SignUpInputs/index.jsx
  src/components/UserDetail/index.jsx
  src/screens/Profile/index.jsx
  src/utils/axios.js
Labels: awaiting-review
